apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: aws-account-shredder-0.0.1
  namespace: placeholder
  annotations:
    categories: A list of comma separated categories that your operator falls under.
    certified: "false"
    description: AWS account shredder.
    containerImage: quay.io/app-sre/aws-account-shredder:latest
    createdAt: "2019-07-21T17:34:33Z"
    support: Amol Gautam
spec:
  displayName: aws-account-shredder
  description: AWS account shredder.
  keywords:
    - kubernetes
    - openshift
    - multi-cluster
    - cluster
  version: 0.0.1
  provider:
    name: Red Hat, Inc
  maturity: alpha
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: false
    - type: AllNamespaces
      supported: false
  install:
    strategy: deployment
    spec:
      clusterPermissions:
        - serviceAccountName: aws-account-shredder
          # Rules will be added here by the generate-operator-bundle.py script.
      deployments:
        - name: aws-account-shredder
          # Deployment spec will be added here by the generate-operator-bundle.py script.
  customresourcedefinitions:
    owned:
    # CRD's will be added here by the generate-operator-bundle.py